name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get update -q && sudo apt-get install -qy git build-essential curl zip ccache junit4 libkrb5-dev nasm graphviz python3 python3-dev python3-setuptools qtbase5-dev libkf5coreaddons-dev libcurl4-openssl-dev libkf5i18n-dev libkf5config-dev libkf5windowsystem-dev libkf5kio-dev libqt5x11extras5-dev autoconf libcups2-dev libfontconfig1-dev gperf openjdk-17-jdk doxygen libxslt1-dev xsltproc libxml2-utils libxrandr-dev libx11-dev bison flex libgtk-3-dev ant ant-optional libnss3-dev libavahi-client-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxtst-dev libxt-dev
        git clone --depth=1 https://github.com/LibreOffice/core lo
        cd lo

        ./autogen.sh \
            --disable-avahi \
            --disable-cairo-canvas \
            --disable-coinmp \
            --disable-cups \
            --disable-cve-tests \
            --disable-dbus \
            --disable-dconf \
            --disable-dependency-tracking \
            --disable-evolution2 \
            --disable-dbgutil \
            --disable-extension-integration \
            --disable-extension-update \
            --disable-firebird-sdbc \
            --disable-gio \
            --disable-gstreamer-1-0 \
            --disable-gtk3 \
            --disable-introspection \
            --disable-largefile \
            --disable-lotuswordpro \
            --disable-lpsolve \
            --disable-odk \
            --disable-ooenv \
            --disable-pch \
            --disable-postgresql-sdbc \
            --disable-python \
            --disable-randr \
            --disable-report-builder \
            --disable-scripting-beanshell \
            --disable-scripting-javascript \
            --disable-sdremote \
            --disable-sdremote-bluetooth \
            --enable-mergelibs \
            --with-galleries="no" \
            --with-system-curl \
            --with-system-expat \
            --with-system-libxml \
            --with-system-nss \
            --with-system-openssl \
            --with-theme="no" \
            --without-export-validation \
            --without-fonts \
            --without-helppack-integration \
            --without-java \
            --without-junit \
            --without-krb5 \
            --without-myspell-dicts \
            --without-system-dicts \
            --without-x

        find .

        make

        find .
